//
//  LeaguesByCountry.swift
//  DiplomProject_LiveScoreFootball
//
//  Created by admin on 10.08.22.
//

import Foundation

struct DataLeagues: Codable {
    let status: Int
    let data: [LeaguesByCountry]
}

struct LeaguesByCountry: Codable {
    let leagueID, leagueName: String
    let countryCode: CountryCode
    let leagueCode: String

    enum CodingKeys: String, CodingKey {
        case leagueID = "league_id"
        case leagueName = "league_name"
        case countryCode = "country_code"
        case leagueCode = "league_code"
    }
}

enum CountryCode: String, Codable {
    case england = "england"
    case spain = "spain"
    case italy = "italy"
    case germany = "germany"
    case france = "france"
    case holland = "holland"
    case scotland = "scotland"
    case championsLeague =  "champions-league"
    case europaLeague = "europa-league"
    case worldCup = "world-cup"
    case uefaNationsLeague = "uefa-nations-league"
    case uefaWomensChampionsLeague = "uefa-women-s-champions-league"
    case womensWorldCup = "womens-world-cup"
    case euroWomen = "euro-women"
    case euroUnder21 = "euro-under-21"
    case africaCupOfNations  = "africa-cup-of-nations"
    case africanNationsChampionship = "african-nations-championship"
    case copaAmerica = "copa-america"
    case concacafNationsLeague = "concacaf-nations-league"
    case international = "intl"
    case africa = "africa"
    case asia = "asia"
    case concacaf = "concacaf"
    case oceania = "oceania"
    case southAmerica = "south-america"
    case summerOlympics2012 = "summer-olympics-2012"
    case summerOlympics2012women = "summer-olympics-2012-women"
    case albania = "albania"
    case algeria = "algeria"
    case andora = "andorra"
    case angola = "angola"
    case argentina = "argentina"
    case armenia = "armenia"
    case australia = "australia"
    case austria = "austria"
    case azerbaijan = "azerbaijan"
    case bahrain = "bahrain"
    case bangladesh = "bangladesh"
    case belarus = "belarus"
    case belgium = "belgium"
    case bolivia = "bolivia"
    case bosnia = "bosnia"
    case botswana = "botswana"
    case brazil = "brazil"
    case bulgaria = "bulgaria"
    case cambodia = "cambodia"
    case cameroon = "cameroon"
    case canada = "canada"
    case chile = "chile"
    case china = "china"
    case colombia = "colombia"
    case congo = "congo"
    case costaRica = "costa-rica"
    case croatia = "croatia"
    case cuba = "cuba"
    case cyprus = "cyprus"
    case czechRepublic = "czech-republic"
    case denmark = "denmark"
    case drCongo = "dr-congo"
    case ecuador = "ecuador"
    case egypt = "egypt"
    case elSalvador = "el-salvador"
    case estonia = "estonia"
    case ethiopia = "ethiopia"
    case faroeIslands = "faroe-islands"
    case finland = "finland"
    case georgia = "georgia"
    case ghana = "ghana"
    case gibraltar = "gibraltar"
    case greece = "greece"
    case guatemala = "guatemala"
    case honduras = "honduras"
    case hongKong = "hong-kong"
    case hungary = "hungary"
    case iceland = "iceland"
    case india = "india"
    case indonesia = "indonesia"
    case iran = "iran"
    case iraq = "iraq"
    case ireland = "ireland"
    case israel = "israel"
    case ivoryCoast = "ivory-coast"
    case jamaica = "jamaica"
    case japan = "japan"
    case jordan = "jordan"
    case kazakhstan = "kazakhstan"
    case kenya = "kenya"
    case kosovo = "kosovo"
    case kuwait = "kuwait"
    case latvia = "latvia"
    case lebanon = "lebanon"
    case liechtenstein = "liechtenstein"
    case lithuania = "lithuania"
    case luxembourg = "luxembourg"
    case malaysia = "malaysia"
    case malta = "malta"
    case mexico = "mexico"
    case moldova = "moldova"
    case mongolia = "mongolia"
    case montenegro = "montenegro"
    case morocco = "morocco"
    case myanmar = "myanmar"
    case newZealand = "new-zealand"
    case nicaragua = "nicaragua"
    case nigeria = "nigeria"
    case macedonia = "macedonia"
    case northernIreland = "northern-ireland"
    case norway = "norway"
    case oman = "oman"
    case palestine = "palestine"
    case panama = "panama"
    case paraguay = "paraguay"
    case peru = "peru"
    case philippines = "philippines"
    case poland = "poland"
    case portugal = "portugal"
    case qatar = "qatar"
    case koreaRepublic = "korea-republic"
    case romania = "romania"
    case russia = "russia"
    case rwanda = "rwanda"
    case sanMarino = "san-marino"
    case saudiArabia = "saudi-arabia"
    case senegal = "senegal"
    case serbia = "serbia"
    case singapore = "singapore"
    case slovakia = "slovakia"
    case slovenia = "slovenia"
    case southAfrica = "south-africa"
    case sweden = "sweden"
    case switzerland = "switzerland"
    case syria = "syria"
    case taiwan = "taiwan"
    case tanzania = "tanzania"
    case thailand = "thailand"
    case trinidadAndTobago = "trinidad-and-tobago"
    case tunisia = "tunisia"
    case turkey = "turkey"
    case turkmenistan = "turkmenistan"
    case uganda = "uganda"
    case ukraine = "ukraine"
    case unitedArabEmirates = "united-arab-emirates"
    case uruguay = "uruguay"
    case usa = "usa"
    case uzbekistan = "uzbekistan"
    case venezuela = "venezuela"
    case vietnam = "vietnam"
    case wales = "wales"
    case zambia = "zambia"
    case zimbabwe = "zimbabwe"
    case euroU192021 = "euro-u-19-2021"
    case euroU19Women = "euro-u-19-women"
    case euroU17Women = "euro-u-17-women"
    
}
